# ratchet_consensus.py — the agreement rules, lifted out to be copied.
#
# GENERATED by scripts/lift.py from contracts/ratchet.py. Do not edit by hand:
# tests/test_logic.py compares the two parsed trees function by function, so an
# edit here fails the suite rather than quietly claiming a provenance it does
# not have.
#
# GenLayer contracts run as ONE Python file inside the GenVM. There is no pip
# install and no cross-file import at deploy time, so this is not a module you
# import: it is a curated block. contracts/ratchet.py already inlines these
# helpers. This file exists so the rules can be read and lifted into another
# project without reading a whole contract first.
#
# Everything here is pure. No storage, no network, no model. That is the point:
# these are the functions a validator runs to decide whether two nodes agreed,
# and a function that decides agreement must be deterministic or it decides
# nothing at all.
#
# ratchet_agrees is SYMMETRIC: agrees(a, b) == agrees(b, a). An asymmetric
# agreement rule makes consensus depend on who happened to be elected leader,
# which is a subtle and very unpleasant bug.
#
# The one idea worth lifting is reconcile(). The leader asks its question in
# both directions and folds its OWN disagreement into `unclear` before any node
# compares anything, so the uncertainty is carried by the value that gets
# stored rather than by a tolerance in the agreement rule. A tolerant rule lets
# two nodes settle while privately holding different views of what the caller
# should do next, and the record then reads as decisive.


# ---------------------------------------------------------------------------
# Deterministic helpers. Pure, module level, unit tested in tests/test_logic.py
# ---------------------------------------------------------------------------

NARROWER = "narrower"   # the revision binds its author to more on this point
SAME = "same"           # unchanged in effect, however it is worded
BROADER = "broader"     # binds to less, INCLUDING by no longer saying anything
UNCLEAR = "unclear"     # the leader's own two passes did not mirror
TOKENS = (NARROWER, SAME, BROADER, UNCLEAR)
MODEL_TOKENS = (NARROWER, SAME, BROADER)   # what a prompt may legally return
TIGHTENED = "tightened"     # at least one dimension narrower, none loosened
RESTATED = "restated"       # every dimension the same. valid, changes nothing
BROADENED = "broadened"     # at least one dimension loosened. refused
INDETERMINATE = "indeterminate"   # at least one dimension unclear. refused
VERDICTS = (TIGHTENED, RESTATED, BROADENED, INDETERMINATE)
MAX_DIMENSIONS = 12     # per commitment, so one prompt stays bounded
MAX_DELEGATES = 16      # per commitment, so the authority scan stays bounded
MAX_TEXT = 800
MAX_LABEL = 120
MAX_DIMENSION = 80
MAX_REASON = 160


def looks_like_address(raw):
    """Is this a 20 byte hex address, before anything tries to parse it?

    Address() raises a bare Exception on a malformed value, which the runtime
    reports as a contract error rather than as the caller's mistake. Checking
    the shape first turns "the contract crashed" into "that is not an address",
    which is the difference between a bug report and a typo.
    """
    s = str(raw).strip()
    if len(s) != 42 or not s.startswith("0x"):
        return False
    for ch in s[2:]:
        if ch not in "0123456789abcdefABCDEF":
            return False
    return True


def normalise_token(raw):
    """One model answer to a legal token, or empty for anything unusable.

    Empty rather than a guess. A token invented here would be indistinguishable
    downstream from one the model actually returned, and it would be wrong on
    exactly the dimensions the model found hardest.
    """
    s = str(raw).strip().lower()
    if s in MODEL_TOKENS:
        return s
    return ""


def parse_vector(text, n):
    """Pipe joined tokens to a list of length n, or None if it is unusable.

    None is not the same as a vector of empties: it means the answer did not
    have the right shape at all, and a validator must reject it rather than
    compare it.
    """
    parts = str(text).split("|")
    if len(parts) != n:
        return None
    out = []
    for p in parts:
        t = normalise_token(p)
        if t == "":
            return None
        out.append(t)
    return out


def mirrors(forward, reverse):
    """The two passes agree about direction, read from opposite ends.

    If the revision is narrower on a dimension then the original must be
    broader on that same dimension. Anything else means the leader answered
    the same question two different ways, and no amount of consensus between
    NODES can repair a leader that does not agree with itself.
    """
    if forward == NARROWER:
        return reverse == BROADER
    if forward == BROADER:
        return reverse == NARROWER
    if forward == SAME:
        return reverse == SAME
    return False


def reconcile(forward, reverse):
    """Fold the leader's own two passes into ONE stored token per dimension.

    This is the whole design in four lines. A dimension the leader is not
    self-consistent about becomes `unclear` HERE, before any node compares
    anything, so the uncertainty is carried by the value that gets stored
    rather than by a tolerance in the agreement rule.

    A tolerant agreement rule would let two nodes settle while privately
    holding different views of what the caller should do, and the record would
    look decisive. This cannot: `unclear` is visible in the vector, in the
    verdict, and in the refusal.
    """
    if len(forward) != len(reverse):
        return None
    out = []
    for i in range(len(forward)):
        if mirrors(forward[i], reverse[i]):
            out.append(forward[i])
        else:
            out.append(UNCLEAR)
    return out


def classify(vector):
    """Turn a reconciled vector into a verdict. Pure and total.

    The four outcomes are not degrees of one thing. They are different facts
    about the pair of texts:

        tightened      binds to more somewhere and to less nowhere
        restated       identical in effect, however differently it is worded
        broadened      binds to less somewhere, which is what a ratchet exists
                       to catch, INCLUDING when it happens by dropping a clause
                       rather than by contradicting one
        indeterminate  the leader could not answer the same question the same
                       way twice on some dimension
    """
    if len(vector) == 0:
        return INDETERMINATE
    if UNCLEAR in vector:
        return INDETERMINATE
    if BROADER in vector:
        return BROADENED
    if NARROWER in vector:
        return TIGHTENED
    return RESTATED


def loosened_dimensions(vector):
    """Indices of the dimensions that got weaker. Sorted, for a stable string.

    Sorted rather than in discovery order: two nodes finding the same set in a
    different order must produce the same stored value, or banding the answer
    achieves nothing.
    """
    out = []
    for i in range(len(vector)):
        if vector[i] == BROADER:
            out.append(i)
    return sorted(out)


def structurally_sound(vector, n):
    """Layer 1 of the validator. Costs nothing, runs before any prompt.

    Two ways a proposal is malformed regardless of what any model thinks: the
    wrong number of dimensions, or a token that is not one a prompt may return.
    `unclear` is legal in a STORED vector and is not legal here, because a
    validator receives the leader's reconciled answer and must be able to tell
    "the leader was unsure" from "the leader sent rubbish".
    """
    if vector is None:
        return False
    if len(vector) != n or n == 0:
        return False
    for t in vector:
        if t not in TOKENS:
            return False
    return True


def ratchet_agrees(mine, theirs, n):
    """Layer 2. Exact equality on the whole vector, and nothing else.

    Symmetric by construction: both sides go down the same parse and the
    comparison is an equality, so agrees(a, b) == agrees(b, a). An asymmetric
    agreement rule makes consensus depend on who happened to be elected leader,
    which is a subtle and very unpleasant bug.

    There is deliberately no tolerance here. A rule that forgave one dimension
    would let two nodes settle on a record that says `tightened` while one of
    them believed a clause had been dropped.
    """
    a = mine if isinstance(mine, list) else parse_stored(mine, n)
    b = theirs if isinstance(theirs, list) else parse_stored(theirs, n)
    if not structurally_sound(a, n) or not structurally_sound(b, n):
        return False
    return a == b


def parse_stored(text, n):
    """Like parse_vector, but `unclear` is legal: this reads a RECONCILED vector."""
    parts = str(text).split("|")
    if len(parts) != n:
        return None
    out = []
    for p in parts:
        s = str(p).strip().lower()
        if s not in TOKENS:
            return None
        out.append(s)
    return out


def sanitise_reason(raw, limit=MAX_REASON):
    """Clean a leader supplied explanation before it is stored.

    These strings are NOT part of consensus, deliberately: two honest readers
    describe the same loosening differently, and comparing prose would stall
    every judgment. That means a leader chooses them freely, so they are
    treated as untrusted text on the way IN rather than on the way out.
    Nothing in this contract acts on them.
    """
    out = []
    for ch in str(raw):
        if ch in "<>{}\\`":
            continue
        if ord(ch) < 32 or ord(ch) == 127:
            ch = " "
        out.append(ch)
    return " ".join("".join(out).split())[:limit]


def clean_line(raw, limit):
    """A single line of caller text, whitespace collapsed, capped."""
    return " ".join(str(raw).split())[:limit]


def split_dimensions(text):
    """Pipe joined dimension names to a list, empties dropped."""
    out = []
    for part in str(text).split("|"):
        s = clean_line(part, MAX_DIMENSION)
        if s != "":
            out.append(s)
    return out


def build_prompt(label, numbered_dimensions, first_text, second_text, first_name, second_name):
    """One comparison, in one direction.

    The direction is carried by which text is named first, and the two calls
    differ ONLY in that. Building both directions from one template is what
    makes the mirror test meaningful: an asymmetry in the wording would show up
    as a disagreement the leader can never resolve, and every dimension would
    come back unclear.
    """
    return f"""You are comparing two versions of a public commitment made by {label}.

DIRECTION: judge {second_name} against {first_name}.

{first_name}:
{first_text}

{second_name}:
{second_text}

For each numbered dimension below, decide what {second_name} does compared to the
other text:

{numbered_dimensions}

Answer with exactly one word per dimension:

  narrower  {second_name} binds the author to MORE on this dimension: a
            stricter limit, a firmer promise, fewer exceptions.
  same      no difference in what the author is bound to, however differently
            it is worded.
  broader   {second_name} binds the author to LESS on this dimension: a looser
            limit, more exceptions, OR it no longer addresses this dimension
            at all. Saying nothing is broader than making a promise.

Judge only what the author is bound to. Tone, length, formatting and
readability are not dimensions of a commitment.

Return json: {{"tokens": "same|narrower|...", "because": "<= 25 words"}}
with exactly one token per dimension, in order, joined by a pipe."""
