"""Regenerate lib/ratchet_consensus.py from the contract.

    python scripts/lift.py

The lifted module claims to be the agreement rules "as the contract runs them".
Maintaining it by hand makes that claim false the first time somebody edits one
side, and a copied rule that no deployed contract uses is worse than no copy at
all -- it is a rule with a provenance it has not earned.

So the copy is generated, and tests/test_logic.py::TestLibParity compares the
two parsed trees function by function. Editing the contract and forgetting to
run this turns into a failing test rather than into a quiet lie.
"""

import ast
import pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
CONTRACT = ROOT / "contracts" / "ratchet.py"
OUT = ROOT / "lib" / "ratchet_consensus.py"

CONSTANTS = ["NARROWER", "SAME", "BROADER", "UNCLEAR", "TOKENS", "MODEL_TOKENS",
             "TIGHTENED", "RESTATED", "BROADENED", "INDETERMINATE", "VERDICTS",
             "MAX_DIMENSIONS", "MAX_DELEGATES", "MAX_TEXT", "MAX_LABEL",
             "MAX_DIMENSION", "MAX_REASON"]

FUNCTIONS = ["looks_like_address", "normalise_token", "parse_vector", "mirrors",
             "reconcile", "classify", "loosened_dimensions", "structurally_sound",
             "ratchet_agrees", "parse_stored", "sanitise_reason", "clean_line",
             "split_dimensions", "build_prompt"]

HEADER = '''# ratchet_consensus.py — the agreement rules, lifted out to be copied.
#
# GENERATED by scripts/lift.py from contracts/ratchet.py. Do not edit by hand:
# tests/test_logic.py compares the two parsed trees function by function, so an
# edit here fails the suite rather than quietly claiming a provenance it does
# not have.
#
# GenLayer contracts run as ONE Python file inside the GenVM. There is no pip
# install and no cross-file import at deploy time, so this is not a module you
# import: it is a curated block. contracts/ratchet.py already inlines these
# helpers. This file exists so the rules can be read and lifted into another
# project without reading a whole contract first.
#
# Everything here is pure. No storage, no network, no model. That is the point:
# these are the functions a validator runs to decide whether two nodes agreed,
# and a function that decides agreement must be deterministic or it decides
# nothing at all.
#
# ratchet_agrees is SYMMETRIC: agrees(a, b) == agrees(b, a). An asymmetric
# agreement rule makes consensus depend on who happened to be elected leader,
# which is a subtle and very unpleasant bug.
#
# The one idea worth lifting is reconcile(). The leader asks its question in
# both directions and folds its OWN disagreement into `unclear` before any node
# compares anything, so the uncertainty is carried by the value that gets
# stored rather than by a tolerance in the agreement rule. A tolerant rule lets
# two nodes settle while privately holding different views of what the caller
# should do next, and the record then reads as decisive.


# ---------------------------------------------------------------------------
# Deterministic helpers. Pure, module level, unit tested in tests/test_logic.py
# ---------------------------------------------------------------------------

'''


def main():
    src = CONTRACT.read_text(encoding="utf-8")
    tree = ast.parse(src)
    lines = src.splitlines(keepends=True)

    def segment(node):
        return "".join(lines[node.lineno - 1:node.end_lineno]).rstrip("\n")

    parts = []
    for name in CONSTANTS:
        for n in tree.body:
            if isinstance(n, ast.Assign) and any(
                    isinstance(t, ast.Name) and t.id == name for t in n.targets):
                parts.append(segment(n))
                break
        else:
            raise SystemExit(f"the contract no longer defines {name}")

    fns = []
    for name in FUNCTIONS:
        for n in tree.body:
            if isinstance(n, ast.FunctionDef) and n.name == name:
                fns.append(segment(n))
                break
        else:
            raise SystemExit(f"the contract no longer defines {name}()")

    OUT.write_text(
        HEADER + "\n".join(parts) + "\n\n\n" + "\n\n\n".join(fns) + "\n",
        encoding="utf-8",
    )
    print(f"  {OUT.relative_to(ROOT)}: {len(CONSTANTS)} constants, {len(FUNCTIONS)} functions")


if __name__ == "__main__":
    main()
